//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService.EmailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailService.IEmailService")]
    public interface IEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SayHello", ReplyAction="http://tempuri.org/IEmailService/SayHelloResponse")]
        string SayHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SayHello", ReplyAction="http://tempuri.org/IEmailService/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        bool SendEmail(string toEmails, System.Collections.Generic.List<string> body, string template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        System.Threading.Tasks.Task<bool> SendEmailAsync(string toEmails, System.Collections.Generic.List<string> body, string template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmailWithDetails", ReplyAction="http://tempuri.org/IEmailService/SendEmailWithDetailsResponse")]
        bool SendEmailWithDetails(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmailWithDetails", ReplyAction="http://tempuri.org/IEmailService/SendEmailWithDetailsResponse")]
        System.Threading.Tasks.Task<bool> SendEmailWithDetailsAsync(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEmailService/SendEmailOneWay")]
        void SendEmailOneWay(string toEmails, System.Collections.Generic.List<string> body, string template);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEmailService/SendEmailOneWay")]
        System.Threading.Tasks.Task SendEmailOneWayAsync(string toEmails, System.Collections.Generic.List<string> body, string template);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEmailService/SendEmailWithDetailsOneWay")]
        void SendEmailWithDetailsOneWay(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEmailService/SendEmailWithDetailsOneWay")]
        System.Threading.Tasks.Task SendEmailWithDetailsOneWayAsync(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailServiceChannel : Afiniti.GRM.SecurityService.EmailService.IEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceClient : System.ServiceModel.ClientBase<Afiniti.GRM.SecurityService.EmailService.IEmailService>, Afiniti.GRM.SecurityService.EmailService.IEmailService {
        
        public EmailServiceClient() {
        }
        
        public EmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello() {
            return base.Channel.SayHello();
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync() {
            return base.Channel.SayHelloAsync();
        }
        
        public bool SendEmail(string toEmails, System.Collections.Generic.List<string> body, string template) {
            return base.Channel.SendEmail(toEmails, body, template);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailAsync(string toEmails, System.Collections.Generic.List<string> body, string template) {
            return base.Channel.SendEmailAsync(toEmails, body, template);
        }
        
        public bool SendEmailWithDetails(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template) {
            return base.Channel.SendEmailWithDetails(fromEmail, toEmails, emailSubject, bccEmails, ccEmails, body, template);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailWithDetailsAsync(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template) {
            return base.Channel.SendEmailWithDetailsAsync(fromEmail, toEmails, emailSubject, bccEmails, ccEmails, body, template);
        }
        
        public void SendEmailOneWay(string toEmails, System.Collections.Generic.List<string> body, string template) {
            base.Channel.SendEmailOneWay(toEmails, body, template);
        }
        
        public System.Threading.Tasks.Task SendEmailOneWayAsync(string toEmails, System.Collections.Generic.List<string> body, string template) {
            return base.Channel.SendEmailOneWayAsync(toEmails, body, template);
        }
        
        public void SendEmailWithDetailsOneWay(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template) {
            base.Channel.SendEmailWithDetailsOneWay(fromEmail, toEmails, emailSubject, bccEmails, ccEmails, body, template);
        }
        
        public System.Threading.Tasks.Task SendEmailWithDetailsOneWayAsync(string fromEmail, string toEmails, string emailSubject, string bccEmails, string ccEmails, System.Collections.Generic.List<string> body, string template) {
            return base.Channel.SendEmailWithDetailsOneWayAsync(fromEmail, toEmails, emailSubject, bccEmails, ccEmails, body, template);
        }
    }
}
