//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationPermission_Assignment
    {
        public int AppPermissionId { get; set; }
        public Nullable<System.Guid> AppPermissionKey { get; set; }
        public Nullable<System.Guid> AppKey { get; set; }
        public Nullable<System.Guid> PermissionKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
