   
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;

namespace Afiniti.GRM.SecurityService
{
    public partial class GRMSecurityEntities : ObjectContext
    {
        public const string ConnectionString = "name=GRMSecurityEntities";
        public const string ContainerName = "GRMSecurityEntities";
    
        #region Constructors
    
        public GRMSecurityEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public GRMSecurityEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public GRMSecurityEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Permission_Levels> Permission_Levels
        {
            get { return _permission_Levels  ?? (_permission_Levels = CreateObjectSet<Permission_Levels>("Permission_Levels")); }
        }
        private ObjectSet<Permission_Levels> _permission_Levels;
    
        public ObjectSet<PermissionType> PermissionTypes
        {
            get { return _permissionTypes  ?? (_permissionTypes = CreateObjectSet<PermissionType>("PermissionTypes")); }
        }
        private ObjectSet<PermissionType> _permissionTypes;
    
        public ObjectSet<RolePermission_Template> RolePermission_Template
        {
            get { return _rolePermission_Template  ?? (_rolePermission_Template = CreateObjectSet<RolePermission_Template>("RolePermission_Template")); }
        }
        private ObjectSet<RolePermission_Template> _rolePermission_Template;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;
    
        public ObjectSet<User_Attributes_Security> User_Attributes_Security
        {
            get { return _user_Attributes_Security  ?? (_user_Attributes_Security = CreateObjectSet<User_Attributes_Security>("User_Attributes_Security")); }
        }
        private ObjectSet<User_Attributes_Security> _user_Attributes_Security;
    
        public ObjectSet<UserPermission_Assignment> UserPermission_Assignment
        {
            get { return _userPermission_Assignment  ?? (_userPermission_Assignment = CreateObjectSet<UserPermission_Assignment>("UserPermission_Assignment")); }
        }
        private ObjectSet<UserPermission_Assignment> _userPermission_Assignment;
    
        public ObjectSet<UserRole_Rel> UserRole_Rel
        {
            get { return _userRole_Rel  ?? (_userRole_Rel = CreateObjectSet<UserRole_Rel>("UserRole_Rel")); }
        }
        private ObjectSet<UserRole_Rel> _userRole_Rel;
    
        public ObjectSet<UserSession_Logs> UserSession_Logs
        {
            get { return _userSession_Logs  ?? (_userSession_Logs = CreateObjectSet<UserSession_Logs>("UserSession_Logs")); }
        }
        private ObjectSet<UserSession_Logs> _userSession_Logs;
    
        public ObjectSet<UserSession> UserSessions
        {
            get { return _userSessions  ?? (_userSessions = CreateObjectSet<UserSession>("UserSessions")); }
        }
        private ObjectSet<UserSession> _userSessions;
    
        public ObjectSet<ContactAttribute> ContactAttributes
        {
            get { return _contactAttributes  ?? (_contactAttributes = CreateObjectSet<ContactAttribute>("ContactAttributes")); }
        }
        private ObjectSet<ContactAttribute> _contactAttributes;
    
        public ObjectSet<SecurityApp> SecurityApps
        {
            get { return _securityApps  ?? (_securityApps = CreateObjectSet<SecurityApp>("SecurityApps")); }
        }
        private ObjectSet<SecurityApp> _securityApps;
    
        public ObjectSet<SecurityApps_Configuration> SecurityApps_Configuration
        {
            get { return _securityApps_Configuration  ?? (_securityApps_Configuration = CreateObjectSet<SecurityApps_Configuration>("SecurityApps_Configuration")); }
        }
        private ObjectSet<SecurityApps_Configuration> _securityApps_Configuration;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<RequestLogs> RequestLogs
        {
            get { return _requestLogs  ?? (_requestLogs = CreateObjectSet<RequestLogs>("RequestLogs")); }
        }
        private ObjectSet<RequestLogs> _requestLogs;
    
        public ObjectSet<ApplicationPermission_Assignment> ApplicationPermission_Assignment
        {
            get { return _applicationPermission_Assignment  ?? (_applicationPermission_Assignment = CreateObjectSet<ApplicationPermission_Assignment>("ApplicationPermission_Assignment")); }
        }
        private ObjectSet<ApplicationPermission_Assignment> _applicationPermission_Assignment;
    
        public ObjectSet<Permissions> Permissions
        {
            get { return _permissions  ?? (_permissions = CreateObjectSet<Permissions>("Permissions")); }
        }
        private ObjectSet<Permissions> _permissions;

        #endregion

    }
}
