//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_Levels
    {
        public int PermissionLevelId { get; set; }
        public System.Guid PermissionLevelKey { get; set; }
        public string PermissionLevelName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    }
}
