//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int PermissionId { get; set; }
        public System.Guid PermissionKey { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Key { get; set; }
        public System.Guid PermissionTypeKey { get; set; }
        public System.Guid PermissionLevelKey { get; set; }
        public bool IsActive { get; set; }
        public string CSSClass { get; set; }
        public string DisplayText { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.Guid> ParentKey { get; set; }
    }
}
