//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLogs
    {
        public long RequestId { get; set; }
        public string RequestURL { get; set; }
        public string RequestedBy { get; set; }
        public string CallerApplication { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
