//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityApps_Configuration
    {
        public int ConfigId { get; set; }
        public System.Guid AppKey { get; set; }
        public string ConfigKey { get; set; }
        public string ConfigValue { get; set; }
        public int ConfigType { get; set; }
    }
}
