//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Attributes_Security
    {
        public int AttributeSecurityId { get; set; }
        public System.Guid PersonKey { get; set; }
        public System.Guid AttributeKey { get; set; }
        public byte AccessLevel { get; set; }
    }
}
