//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession_Logs
    {
        public int UserSessionLogId { get; set; }
        public int SessionId { get; set; }
        public string AccessURL { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
