//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public System.Guid UserKey { get; set; }
        public string UserName { get; set; }
        public bool CanImpersonate { get; set; }
        public bool IsActive { get; set; }
        public short ApprovalStatus { get; set; }
        public Nullable<System.Guid> UserRemoteKey { get; set; }
        public string SecQ { get; set; }
        public string SecA { get; set; }
        public string Email { get; set; }
        public string OutlookGenieAttrMapping { get; set; }
        public short GenieMobileApproval { get; set; }
        public short JiraMobileApproval { get; set; }
        public short ETLApprovalStatus { get; set; }
        public short PMOApproval { get; set; }
        public short DMSMACApproval { get; set; }
        public bool IsAdmin { get; set; }
    }
}
