//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.GRM.SecurityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public int SessionId { get; set; }
        public string ASPNETSessionID { get; set; }
        public System.Guid UserKey { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Expired { get; set; }
        public string IPAddress { get; set; }
        public bool IsActive { get; set; }
        public byte SessionStatus { get; set; }
        public Nullable<bool> MarkedAsSuspicious { get; set; }
        public string CrowdToken { get; set; }
    }
}
